[acme]
directory_url = "https://acme-staging-v02.api.letsencrypt.org/directory"
user_email = "your@email.tld"
refresh_threshold = 15
# See https://go-acme.github.io/lego/dns/
challenge_provider_name = "route53"

[appliances.my-netapp-cluster]
type = "netapp"
domains = [
    "netapp.domain.tld"
]
url = "https://1.2.3.4"
validate_certs = false
username = "admin"
password = "admin"

[appliances.my-netapp-cluster.custom]
cert_name = "test-le-cert"
svm_name = "cert-test"

[appliances.my-adc-cluster]
type = "citrix_adc"
domains = [
    "citrix-adc.domain.tld"
]
url = "http://1.2.3.4"
validate_certs = false
username = "nsroot"
password = "nsroot"

[appliances.my-adc-cluster.custom]
filename_cert = "le_cert.pem"
filename_key = "le_key.pem"
path_ssl = "/nsconfig/ssl/"
cert_name = "test-le-cert"
